### ISSUE TITLE
Cannot install on R 3.5.0

### ISSUE THREAD

**Issue by ms609** [r-lib/cli#595]
I am unable to install "cli" on R 3.5.   I can install other packages from source, so I don't think it's an issue with the system.  And this is a clean install of R 3.5 (though it was installed on this machine previously, so older versions of some packages persist).

I see:

```
* installing *source* package 'cli' ...
** package 'cli' successfully unpacked and MD5 sums checked
** libs
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG        -I../inst/include   -O2 -Wall  -std=gnu99 -mtune=generic -c ansi.c -o ansi.o
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG        -I../inst/include   -O2 -Wall  -std=gnu99 -mtune=generic -c cleancall.c -o cleancall.o
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG        -I../inst/include   -O2 -Wall  -std=gnu99 -mtune=generic -c diff.c -o diff.o
diff.c: In function 'clic_diff_chr':
diff.c:85:7: warning: 'sn' may be used uninitialized in this function [-Wmaybe-uninitialized]
   int sn;
       ^
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG        -I../inst/include   -O2 -Wall  -std=gnu99 -mtune=generic -c errors.c -o errors.o
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG        -I../inst/include   -O2 -Wall  -std=gnu99 -mtune=generic -c glue.c -o glue.o
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG        -I../inst/include   -O2 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG        -I../inst/include   -O2 -Wall  -std=gnu99 -mtune=generic -c inst.c -o inst.o
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG        -I../inst/include   -O2 -Wall  -std=gnu99 -mtune=generic -c keypress-unix.c -o keypress-unix.o
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG        -I../inst/include   -O2 -Wall  -std=gnu99 -mtune=generic -c keypress-win.c -o keypress-win.o
In file included from C:/PROGRA~1/R/R-35~1.0/include/R.h:91:0,
                 from keypress.h:5,
                 from keypress-win.c:8:
C:/PROGRA~1/R/R-35~1.0/include/R_ext/RS.h:55:0: warning: "ERROR" redefined
 #define ERROR   ),error(R_problem_buf);}
 ^
In file included from C:/Rtools/mingw_64/x86_64-w64-mingw32/include/windows.h:71:0,
                 from errors.h:24,
                 from keypress-win.c:7:
C:/Rtools/mingw_64/x86_64-w64-mingw32/include/wingdi.h:75:0: note: this is the location of the previous definition
 #define ERROR 0
 ^
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG        -I../inst/include   -O2 -Wall  -std=gnu99 -mtune=generic -c keypress.c -o keypress.o
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG        -I../inst/include   -O2 -Wall  -std=gnu99 -mtune=generic -c md5.c -o md5.o
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG        -I../inst/include   -O2 -Wall  -std=gnu99 -mtune=generic -c progress-altrep.c -o progress-altrep.o
progress-altrep.c:32:26: fatal error: R_ext/Altrep.h: No such file or directory
 #include <R_ext/Altrep.h>
                          ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-35~1.0/etc/x64/Makeconf:208: progress-altrep.o] Error 1
ERROR: compilation failed for package 'cli'
* removing 'C:/Users/pjjg18/Documents/R/win-library/3.5/cli'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘cli’ had non-zero exit status
```

`sessionInfo()`:
```
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0
```

**Comment by gaborcsardi** [comment]
I can reproduce this on R 3.5.0, but R 3.5.3 does work. Can you try to update to that?

**Comment by ms609** [comment]
I'm trying to debug one of my packages on R 3.5.0, so need to use that specific version.  (Though I'm currently considering dropping support for versions of R that early; perhaps this would strengthen the case!)

CLI's "Depends" entry in the DESCRIPTION file is currently set to R (≥ 3.4) — I wonder whether this ought to be updated to R (≥ 3.5.3), if earlier versions are no longer installable?

**Comment by gaborcsardi** [comment]
We actually test cli on R 3.4.x and 3.5.x, but only the latest versions. It actually works on R 3.5.0 as well on macOS. I vaguely remember that there was a bug in R 3.5.0 that was fixed later. It is possible that we can work around it in cli, IDK.

**Comment by ms609** [comment]
I've got cli running on 3.5.2; if the issue is an underlying R bug, then the [limited use](https://stackoverflow.com/questions/76073914) of R3.5.0 probably doesn't justify further investigation.  Thanks for looking into this.
